name: seek_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  tasks_repository:
    path: packages/tasks_repository
  local_storage_service:
    path: packages/local_storage_service
  dartz: ^0.10.1
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  freezed: ^2.4.5
  build_runner: ^2.4.6
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  mockito: ^5.4.5


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
