name: tasks_repository
description: My new Flutter package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  local_storage_service:
    path: ../local_storage_service

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  freezed: ^2.4.5
  build_runner: ^2.4.6
  json_serializable: ^6.5.4
  mockito: ^5.3.2


